<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <?php include(__DIR__ . '/../Nav/Nav.phtml');?>
    <main>
        <div class= container-lg mt-3>
            <h1>Сайты</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа </th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($data as $key => $value): ?>
                    <tr>
                        <td>
                            <?= htmlspecialchars($value['id'] ?? '') ?>
                        </td>
                        <td>
                            <a href="<?= '/urls/' . htmlspecialchars($value['id'] ?? '') ?>">
                                <?= htmlspecialchars($value['name'] ?? '') ?></td>
                            </a>
                        <td><?=  htmlspecialchars($value["create_at"] ?? '') ?></td>
                        <td><?= htmlspecialchars($value["status_code"] ?? '') ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>