<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
</head>
<body class="min-vh-100 d-flex flex-column">
    <?php include(__DIR__ . '/../Nav/Nav.phtml');?>
    <div class="alert alert-success" role="alert"><?=$flash['success'][0]?></div>
    <main class="flex-grow-1"> 
        <div class="container-lg mt-3">
            <h1>Сайт:<?= htmlspecialchars($name) ?></h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="url">
                    <tbody>
                        <tr>
                            <td>ID</td>
                            <td><?= htmlspecialchars($id)?></td>
                        </tr>
                        <tr>
                            <td>Имя</td>
                            <td><?= htmlspecialchars($name)?></td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td><?= htmlspecialchars($created_at)?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <h2 class="mt-5 mb-3">Проверки</h2>
            <form method='post' action="/urls/<?=$id?>/checks">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>