<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class>
    <nav class="navbar bg-dark navbar-expand-sm bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarID"
                aria-controls="navbarID" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarID">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="/">Главная</a>
                </div>
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="/urls">Сайты</a>
                </div>
            </div>
        </div>
    </nav>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <div class="row">
                <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                    <h1 class ="display-3">Анализатор страницы </h1>
                    <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                    <form action="/urls" method = post class ="row" required>
                      <div class="col-8">
                        <label for="text" class="visually-hidden">Url для проверки</label>
                        <input type="text"
                               name="url[name]"
                               value=""
                               placeholder="https://www.example.com"
                               class="form-control form-control-lg
                                <?php if (isset($errors[0])) : ?>is-invalid<?php endif ?>">
                                <?php if (isset($errors[0])) : ?>
                                    <div class="invalid-feedback"><?= htmlspecialchars($errors[0]) ?></div>
                                <?php endif ?>
                        </div>
                        <div class="col-2">
                            <input class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3"
                                    type="submit"
                                    value="Проверить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>